"""initial schema

Revision ID: e91d131e8b03
Revises: 
Create Date: 2026-06-22 02:25:42.778719
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e91d131e8b03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('affected_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_affected_id'), ['affected_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_created_at'), ['created_at'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_enrolled', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_severity'), ['severity'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('custom_headers_json', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(length=160), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('employee_name', sa.String(length=160), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('snapshot_available', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('manual_reason', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_logs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_sync_status'), ['sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('face_embeddings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('pose_step', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('yaw', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_employee_id'), ['employee_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('webhook_id', sa.String(length=32), nullable=False),
    sa.Column('attendance_log_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('delivery_id', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_attendance_log_id'), ['attendance_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_attendance_log_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_employee_id'))

    op.drop_table('face_embeddings')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_sync_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_machine_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_employee_id'))

    op.drop_table('attendance_logs')
    op.drop_table('webhooks')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_system_logs_event'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))

    op.drop_table('system_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))

    op.drop_table('employees')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_created_at'))

    op.drop_table('backups')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_affected_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
